### ISSUE TITLE
Incorporación de nueva sección

### ISSUE THREAD

**Issue by JoaquinFranich** [xarpdev/portfolio-template#3]
Hola.
Como estas?
Me llamo Joaquin.
Estuve revisando tu portfolio y me parecio un buen trabajo.
Creo que una sección de "Tecnologías" seria una buena incorporación.

**Comment by xarpdev** [comment]
Muchas gracias Joaquín por tu revisión y por tu aporte a mi portfolio!
Queda cerrado este Issues.
